### PR TITLE
Minor fix for short date label

### PR DESCRIPTION
**Pull request by pkbullock**
| Q               | A
| --------------- | ---
| Bug fix?        | [ X]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Minor fix for the short date label for "Wed". Version 1.12.0

### CODE REVIEW

**Comment by pkbullock** [comment]
I noticed on another pull request that there are tags for various versions, this affects all previous versions.  How do I submit PRs for previous versions, sorry bit noobish with GIT/Github?

**Comment by AJIXuMuK** [comment]
Hi @pkbullock,
You should create PRs for the latest version only. 
If your forked repo is out of date then get latest code from upstream, create a new branch based on `dev` branch of the repo, make changes and propose a PR.

**Comment by pkbullock** [comment]
Hi @AJIXuMuK, Thanks. This PR is based on the latest, only forked from dev this morning.

**Comment by estruyf** [comment]
Thanks @pkbullock for fixing this, will merge this soon.

**Pull request merged**
