### PR TITLE
Updated PropertyFieldTermPicker to be able to pick terms as close to the OOB Term picker in sharepoint

### PR DESCRIPTION
**Pull request by spdavid**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Changed ICheckedTerm.Id to ICheckedTerm.Key so it would work as an interface in the BasePicker<T>
Added ICheckedTerm.TermSetName property to interface so it can be shown in the custom rendering of the suggestions of the TermPicker

Changed ICheckedTerm to IPickerTerm for semantic reasons

Created New TermPicker Component Inheriting from BasePicker. Use custom Rendering for suggestions and Tag Rendering. 

Removed Texbox and Added Custom TermPicker Component in the PropertyFieldTermPickerHost

Added Functionality to SPTermStorePickerService to support the TermPicker autocompletion

Note: Might be some breaking changes here. EG. ICheckedTerm namechange and change from ID to Key.  Had to make some decisions here as there were a lot of changes and didn't see a way around it without redundant data. 

Other Notes: When searching terms when limitByGroupNameOrID there can be performance issues with large termsets as i loop through each. There is no group.getTerms method. There may be room for optimization here when I think of something better. 

Sorry for the large pull request. :)

### CODE REVIEW

**Comment by spdavid** [comment]
CircleCI failed. Works on my computer. :)

Seems there is a Node version difference. Not sure if this can be the problem or not.

CircleCI  versions
[13:05:02] Project @pnp/spfx-property-controls version: 1.4.2
[13:05:02] Build tools version: 3.0.5
[13:05:02] Node version: v6.11.5
[13:05:02] Total duration: 14 s

My Versions 
[15:14:36] ==================[ Finished ]==================
[15:14:36] Project @pnp/spfx-property-controls version: 1.4.2
[15:14:36] Build tools version: 3.0.5
[15:14:36] Node version: v8.9.4
[15:14:36] Total duration: 11 s

**Comment by estruyf** [comment]
@spdavid thanks, will take a look at it this week.

It cannot build, because you references this `'../../lib/propertyFields/termPicker/TermSet'` in one of your files. During the build, the lib folder will be empty, so the TermSet file will not exist. These type of imports typically happen with auto-importing. Always be sure to reference files in the `src` folder.

Something I always do is running my jobs like this: `gulp clean && gulp bundle`, that way I'm sure I always start clean and my references are correct. Will update the reference during the tests.

**Comment by estruyf** [comment]
Would you also be able to write the documentation for your control? Current documentation can be found here: https://github.com/SharePoint/sp-dev-fx-property-controls/tree/master/docs/documentation/docs

**Comment by spdavid** [comment]
change to the Lib import fixed the problem. Documentation will be updated soon.

**Comment by spdavid** [comment]
Documentation updated. and one small bug fix for local workbench

**Comment by estruyf** [comment]
@spdavid it got merged. Thanks for the Term Picker updates!

**Comment by AJIXuMuK** [comment]
Awesome job!

**Pull request closed without merging**
