### PR TITLE
Checkbox, Button, Label and Link components with Callout

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | []
| New feature?    | [x]
| New sample?      | []
| Related issues?  | no

#### What's in this Pull Request?

Checkbox, Button, Label and Link components with Callout

screen shot 2017-11-30 at 10 52 24 pm

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks!

Would you also be able to update the documentation?

Will process this next week.

**Comment by AJIXuMuK** [comment]
@estruyf it was my plan from the beginning.
But GitHub doesn't support PRs for Wiki repo...
How do you want to organize the process of editing the documentation?

**Comment by estruyf** [comment]
Documentation has changed to Github pages. You can add your controls to the documentation which you can find here: https://github.com/SharePoint/sp-dev-fx-property-controls/tree/dev/docs/documentation/docs

**Comment by estruyf** [comment]
BTW: the docs are generated with `mkdocs`, you can read more about the process here: https://github.com/SharePoint/sp-dev-fx-property-controls/blob/dev/docs/guides/mpa.md

**Comment by AJIXuMuK** [comment]
@estruyf thanks for the explanation!
Will work on documentation asap.

**Comment by AJIXuMuK** [comment]
@estruyf done!

**Comment by estruyf** [comment]
Thanks again for these controls!

**Pull request merged**
