### PR TITLE
Add ar-sa localization

### LINKED ISSUE #461: Arabic local missing for resource "PropertyControlStrings"
Hello, 

it appears that the localization data is missing for Arabic language. Is this possible to have or plan it in next release please ?

#### Category
- [x] Enhancement
- [x] Bug
- [ ] Question

#### Version
version of the library: [3.6.0]

#### Expected / Desired Behavior / Question
ar-sa.js shipped in package -> dist folder

#### Observed Behavior
Error - [webpack] 'dist':
The selected locale (ar-sa) is not present in the localized data for resource "PropertyControlStrings".

#### Steps to Reproduce
In the built solution the src/loc/ar-sa.js ressource file is present
then 
gulp serve --locale=ar-sa

Thanks!

### PR DESCRIPTION
**Pull request by JeanNetryValere**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X ]
| New sample?      | [ ]
| Related issues?  | fixes #461 

#### What's in this Pull Request?
This request is relative to this issue the missing arabic translations

Only one file added ar-sa.js in /[src](https://github.com/pnp/sp-dev-fx-property-controls/tree/master/src)/loc/

### CODE REVIEW

**Comment by milanholemans** [comment]
Hi @JeanNetryValere, you should target the `dev` branch instead of master. Next to the title of your PR, click 'edit' and change the target branch to `dev`.

**Comment by JeanNetryValere** [comment]
Hello @milanholemans i have an issue to change the target from Master to Dev
image

**Comment by milanholemans** [comment]
Hi @JeanNetryValere seems like you are targetting the wrong branch. At this moment you are trying to merge the dev branch in the master branch. However you should merge **your own branch** into the dev branch of the PnP repo.
I suggest that you just close this PR and open a new one. Then you to your forked repo https://github.com/JeanNetryValere/sp-dev-fx-property-controls and open a new PR from there from **your dev** branch into **PnP repo dev** branch.

**Comment by JeanNetryValere** [comment]
Changing branch to dev

**Pull request closed without merging**
