### PR TITLE
add component "PropertyFieldSitePicker"

### PR DESCRIPTION
**Pull request by nsoeth**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ x ]
| New sample?      | [ ]

#### What's in this Pull Request?

A new control named "PropertyFieldSitePicker". This control allows the user to select one or multiple sites from the SharePoint Search API. Similar to the SitePicker in the official "News"-WebPart.

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @nsoeth,
Thank you for the great addition to the library!
Could you please also update documentation to add details about the new control?
The documentation is located in the same repo in `docs\documentation\docs` folder.

**Comment by nsoeth** [comment]
Hi, I will do it. Might take some time though since I hurt my wrist yesterday. But I will do it asap.

**Comment by nsoeth** [comment]
Hi @AJIXuMuK ,
Managed to write the docs (once mkdocs is set up, it is quite fun writing docs) and also fixed a minor "inconvenience" in the process. Hope this is ok.

**Comment by AJIXuMuK** [comment]
Thank you @nsoeth for the update!

**Pull request merged**
