### PR TITLE
Updated people picker to fully support groups searching.

### PR DESCRIPTION
**Pull request by guido-zambarda**
| Q               | A
| --------------- | ---
| Bug fix?        | [ x ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | 

#### What's in this Pull Request?

Updated the code to support SharePoint sitegroups API.

### CODE REVIEW

**Comment by estruyf** [comment]
HI @guido-zambarda, just tested out the PR, but it seems that no users are being shown anymore. I see the API calls which return valid users/groups, but no data in the picker. Think something might be wrong with the promise logic.

Are you able to validate this on your end?

**Comment by guido-zambarda** [comment]
Hi @estruyf sorry my bad, I forgot a little thing, now it's fixed.

**Comment by AJIXuMuK** [comment]
Hi @guido-zambarda!
It still looks broken...
Current:
current
With your changes:
new

**Comment by guido-zambarda** [comment]
Thanks @AJIXuMuK , can you please try again now?

**Comment by AJIXuMuK** [comment]
Sorry @guido-zambarda but it still doesn't work.
I think the better approach would be to get the code from PnP Reusable React controls and adapt in for the Property Pane. It uses `SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser` endpoint that is the correct approach to search for users and groups as well.
Let me know if you want to work in that direction or I can assign it to myself.

I will close this PR and I've also created a new bug #239 to track that issue.

Thank you very much for the effort and sorry I couldn't approve the PR.

**Pull request closed without merging**
